//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//
//
// <copyright file="Artist.cs" company="Multinerd">
//     Copyright (c) Multinerd. All Rights Reserved.
// </copyright>
//------------------------------------------------------------------------------

using Prism.Mvvm;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace EntityPlus
{
	[GeneratedCode("Tessa", "1.2.3.4")]
	/// <summary> Artist model class.</summary>
	public partial class Artist : BindableBase, IEditableObject
    {
		/// <summary> Initializes a new instance of the <see cref="Artist"/> class.</summary>
		[SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Artist()
		{
			this.Albums = new HashSet<Album>();
        }
	
        /// <summary>Gets or sets the ArtistId property</summary>
		[Key, Required]
		[DisplayName("Artist Id"), Display(Name = "Artist Id")]
		public int ArtistId
        {
            get { return this._ArtistId; }
			set { this.SetProperty(ref this._ArtistId, value); }
        }

		/// <summary> ArtistId backing field</summary>
        private int _ArtistId;


        /// <summary>Gets or sets the Name property</summary>
		[StringLength(120)]
		[DisplayName("Name"), Display(Name = "Name")]
		public string Name
        {
            get { return this._Name; }
			set { this.SetProperty(ref this._Name, value); }
        }

		/// <summary> Name backing field</summary>
        private string _Name;


		/// <summary> Gets or sets the Albums navigation property</summary>
		[SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Album> Albums { get; set; }

	        
		#region IEditableObject

		private Artist_Backup _Artist_Backup;

		private struct Artist_Backup 
		{
			internal int _ArtistId;
			internal string _Name;
		}

        public void BeginEdit()
        {
			_Artist_Backup = new Artist_Backup() 
			{
				_ArtistId = ArtistId,
				_Name = Name,
			};
		}

		public void CancelEdit()
        {
			ArtistId = _Artist_Backup._ArtistId;
			Name = _Artist_Backup._Name;
        }

        public void EndEdit()
        {
			_Artist_Backup._ArtistId = ArtistId;
			_Artist_Backup._Name = Name;
        }

		#endregion
 
		#region SampleData

		public static Artist GetRandomArtist()
        {
            return new Artist()
            {
				ArtistId = 7,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            };
        }

		public static IList<Artist> GetRandomArtists()
        {
			var list = new List<Artist>();
			
			list.Add(new Artist()
			{
				ArtistId = 8,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Artist()
			{
				ArtistId = 9,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Artist()
			{
				ArtistId = 10,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Artist()
			{
				ArtistId = 11,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Artist()
			{
				ArtistId = 12,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			return list;
        }

		#endregion
 

	} 
} 

