//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//
//
// <copyright file="Genre.cs" company="Multinerd">
//     Copyright (c) Multinerd. All Rights Reserved.
// </copyright>
//------------------------------------------------------------------------------

using Prism.Mvvm;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace EntityPlus
{
	[GeneratedCode("Tessa", "1.2.3.4")]
	/// <summary> Genre model class.</summary>
	public partial class Genre : BindableBase, IEditableObject
    {
		/// <summary> Initializes a new instance of the <see cref="Genre"/> class.</summary>
		[SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Genre()
		{
			this.Tracks = new HashSet<Track>();
        }
	
        /// <summary>Gets or sets the GenreId property</summary>
		[Key, Required]
		[DisplayName("Genre Id"), Display(Name = "Genre Id")]
		public int GenreId
        {
            get { return this._GenreId; }
			set { this.SetProperty(ref this._GenreId, value); }
        }

		/// <summary> GenreId backing field</summary>
        private int _GenreId;


        /// <summary>Gets or sets the Name property</summary>
		[StringLength(120)]
		[DisplayName("Name"), Display(Name = "Name")]
		public string Name
        {
            get { return this._Name; }
			set { this.SetProperty(ref this._Name, value); }
        }

		/// <summary> Name backing field</summary>
        private string _Name;


		/// <summary> Gets or sets the Tracks navigation property</summary>
		[SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Track> Tracks { get; set; }

	        
		#region IEditableObject

		private Genre_Backup _Genre_Backup;

		private struct Genre_Backup 
		{
			internal int _GenreId;
			internal string _Name;
		}

        public void BeginEdit()
        {
			_Genre_Backup = new Genre_Backup() 
			{
				_GenreId = GenreId,
				_Name = Name,
			};
		}

		public void CancelEdit()
        {
			GenreId = _Genre_Backup._GenreId;
			Name = _Genre_Backup._Name;
        }

        public void EndEdit()
        {
			_Genre_Backup._GenreId = GenreId;
			_Genre_Backup._Name = Name;
        }

		#endregion
 
		#region SampleData

		public static Genre GetRandomGenre()
        {
            return new Genre()
            {
				GenreId = 25,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            };
        }

		public static IList<Genre> GetRandomGenres()
        {
			var list = new List<Genre>();
			
			list.Add(new Genre()
			{
				GenreId = 26,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Genre()
			{
				GenreId = 27,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Genre()
			{
				GenreId = 28,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Genre()
			{
				GenreId = 29,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Genre()
			{
				GenreId = 30,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			return list;
        }

		#endregion
 

	} 
} 

