//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//
//
// <copyright file="Playlist.cs" company="Multinerd">
//     Copyright (c) Multinerd. All Rights Reserved.
// </copyright>
//------------------------------------------------------------------------------

using Prism.Mvvm;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace EntityPlus
{
	[GeneratedCode("Tessa", "1.2.3.4")]
	/// <summary> Playlist model class.</summary>
	public partial class Playlist : BindableBase, IEditableObject
    {
		/// <summary> Initializes a new instance of the <see cref="Playlist"/> class.</summary>
		[SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
		public Playlist()
		{
			this.Tracks = new HashSet<Track>();
        }
	
        /// <summary>Gets or sets the PlaylistId property</summary>
		[Key, Required]
		[DisplayName("Playlist Id"), Display(Name = "Playlist Id")]
		public int PlaylistId
        {
            get { return this._PlaylistId; }
			set { this.SetProperty(ref this._PlaylistId, value); }
        }

		/// <summary> PlaylistId backing field</summary>
        private int _PlaylistId;


        /// <summary>Gets or sets the Name property</summary>
		[StringLength(120)]
		[DisplayName("Name"), Display(Name = "Name")]
		public string Name
        {
            get { return this._Name; }
			set { this.SetProperty(ref this._Name, value); }
        }

		/// <summary> Name backing field</summary>
        private string _Name;


		/// <summary> Gets or sets the Tracks navigation property</summary>
		[SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
		public virtual ICollection<Track> Tracks { get; set; }

	        
		#region IEditableObject

		private Playlist_Backup _Playlist_Backup;

		private struct Playlist_Backup 
		{
			internal int _PlaylistId;
			internal string _Name;
		}

        public void BeginEdit()
        {
			_Playlist_Backup = new Playlist_Backup() 
			{
				_PlaylistId = PlaylistId,
				_Name = Name,
			};
		}

		public void CancelEdit()
        {
			PlaylistId = _Playlist_Backup._PlaylistId;
			Name = _Playlist_Backup._Name;
        }

        public void EndEdit()
        {
			_Playlist_Backup._PlaylistId = PlaylistId;
			_Playlist_Backup._Name = Name;
        }

		#endregion
 
		#region SampleData

		public static Playlist GetRandomPlaylist()
        {
            return new Playlist()
            {
				PlaylistId = 49,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
            };
        }

		public static IList<Playlist> GetRandomPlaylists()
        {
			var list = new List<Playlist>();
			
			list.Add(new Playlist()
			{
				PlaylistId = 50,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Playlist()
			{
				PlaylistId = 51,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Playlist()
			{
				PlaylistId = 52,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Playlist()
			{
				PlaylistId = 53,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			list.Add(new Playlist()
			{
				PlaylistId = 54,
				Name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
			});

			return list;
        }

		#endregion
 

	} 
} 

