//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maya.AspNetCore.TagHelpers.Metronic.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maya.AspNetCore.TagHelpers.Metronic.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Alert_CloseIconText {
            get {
                return ResourceManager.GetString("Alert_CloseIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        public static string Datatable_Records_NoRecords {
            get {
                return ResourceManager.GetString("Datatable_Records_NoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string Datatable_Records_Processing {
            get {
                return ResourceManager.GetString("Datatable_Records_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_First {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displaying {{start}} - {{end}} of {{total}} records.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_Info {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page number.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_Input {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_Last {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More pages.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_More {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_Next {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_Previous {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select page size.
        /// </summary>
        public static string Datatable_Toolbar_Pagination_Select {
            get {
                return ResourceManager.GetString("Datatable_Toolbar_Pagination_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string DatePicker_Clear {
            get {
                return ResourceManager.GetString("DatePicker_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DatePicker_Today {
            get {
                return ResourceManager.GetString("DatePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string DaterangePicker_Button_Apply {
            get {
                return ResourceManager.GetString("DaterangePicker_Button_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DaterangePicker_Button_Cancel {
            get {
                return ResourceManager.GetString("DaterangePicker_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fr.
        /// </summary>
        public static string Days_Fr {
            get {
                return ResourceManager.GetString("Days_Fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string Days_Fri {
            get {
                return ResourceManager.GetString("Days_Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Days_Friday {
            get {
                return ResourceManager.GetString("Days_Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mo.
        /// </summary>
        public static string Days_Mo {
            get {
                return ResourceManager.GetString("Days_Mo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string Days_Mon {
            get {
                return ResourceManager.GetString("Days_Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Days_Monday {
            get {
                return ResourceManager.GetString("Days_Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sa.
        /// </summary>
        public static string Days_Sa {
            get {
                return ResourceManager.GetString("Days_Sa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string Days_Sat {
            get {
                return ResourceManager.GetString("Days_Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Days_Saturday {
            get {
                return ResourceManager.GetString("Days_Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Su.
        /// </summary>
        public static string Days_Su {
            get {
                return ResourceManager.GetString("Days_Su", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string Days_Sun {
            get {
                return ResourceManager.GetString("Days_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Days_Sunday {
            get {
                return ResourceManager.GetString("Days_Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Th.
        /// </summary>
        public static string Days_Th {
            get {
                return ResourceManager.GetString("Days_Th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string Days_Thu {
            get {
                return ResourceManager.GetString("Days_Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Days_Thursday {
            get {
                return ResourceManager.GetString("Days_Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu.
        /// </summary>
        public static string Days_Tu {
            get {
                return ResourceManager.GetString("Days_Tu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string Days_Tue {
            get {
                return ResourceManager.GetString("Days_Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Days_Tuesday {
            get {
                return ResourceManager.GetString("Days_Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We.
        /// </summary>
        public static string Days_We {
            get {
                return ResourceManager.GetString("Days_We", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string Days_Wed {
            get {
                return ResourceManager.GetString("Days_Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Days_Wednesday {
            get {
                return ResourceManager.GetString("Days_Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here or click to upload..
        /// </summary>
        public static string Dropzone_Title_Clickable {
            get {
                return ResourceManager.GetString("Dropzone_Title_Clickable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop files here..
        /// </summary>
        public static string Dropzone_Title_NotClickable {
            get {
                return ResourceManager.GetString("Dropzone_Title_NotClickable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file ....
        /// </summary>
        public static string Input_File_ChooseFile {
            get {
                return ResourceManager.GetString("Input_File_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string Months_Apr {
            get {
                return ResourceManager.GetString("Months_Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Months_April {
            get {
                return ResourceManager.GetString("Months_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string Months_Aug {
            get {
                return ResourceManager.GetString("Months_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Months_August {
            get {
                return ResourceManager.GetString("Months_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string Months_Dec {
            get {
                return ResourceManager.GetString("Months_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Months_December {
            get {
                return ResourceManager.GetString("Months_December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string Months_Feb {
            get {
                return ResourceManager.GetString("Months_Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Months_February {
            get {
                return ResourceManager.GetString("Months_February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Months_Jan {
            get {
                return ResourceManager.GetString("Months_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Months_January {
            get {
                return ResourceManager.GetString("Months_January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string Months_Jul {
            get {
                return ResourceManager.GetString("Months_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Months_July {
            get {
                return ResourceManager.GetString("Months_July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string Months_Jun {
            get {
                return ResourceManager.GetString("Months_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Months_June {
            get {
                return ResourceManager.GetString("Months_June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string Months_Mar {
            get {
                return ResourceManager.GetString("Months_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Months_March {
            get {
                return ResourceManager.GetString("Months_March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Months_May {
            get {
                return ResourceManager.GetString("Months_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string Months_Nov {
            get {
                return ResourceManager.GetString("Months_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Months_November {
            get {
                return ResourceManager.GetString("Months_November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Months_Oct {
            get {
                return ResourceManager.GetString("Months_Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Months_October {
            get {
                return ResourceManager.GetString("Months_October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string Months_Sep {
            get {
                return ResourceManager.GetString("Months_Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Months_September {
            get {
                return ResourceManager.GetString("Months_September", resourceCulture);
            }
        }
    }
}
